apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus-operator
