apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: default
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  ports:
  - name: http 
    port: 80
    targetPort: 3000
