apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app
  namespace: default
  labels:
    context: backend
spec:
  selector:
    matchLabels:
      app: node-app
  endpoints:
  - port: http